language: php
php:
    - 7.1
    - 7.2
    - 7.3

before_script:
    - composer install --no-interaction

script:
    - vendor/bin/tester tests/cases
    - vendor/bin/phpstan analyse --level 7 src

after_failure:
    # Print *.actual content & log content
    - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done
    - for i in $(find tests -name \*.log); do echo "--- $i"; cat $i; echo; echo; done
